In [95]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
%matplotlib inline

In [96]:
x=pd.read_csv("Train.csv" )

In [97]:
x.head()

INCIDENT_ID       DATE  X_1  X_2  X_3  X_4  X_5  X_6  X_7  X_8  X_9  X_10  \
0   CR_102659  04-JUL-04    0   36   34    2    1    5    6    1    6     1   
1   CR_189752  18-JUL-17    1   37   37    0    0   11   17    1    6     1   
2   CR_184637  15-MAR-17    0    3    2    3    5    1    0    2    3     1   
3   CR_139071  13-FEB-09    0   33   32    2    1    7    1    1    6     1   
4   CR_109335  13-APR-05    0   33   32    2    1    8    3    0    5     1   

   X_11  X_12  X_13  X_14  X_15  MULTIPLE_OFFENSE  
0   174   1.0    92    29    36                 0  
1   236   1.0   103   142    34                 1  
2   174   1.0   110    93    34                 1  
3   249   1.0    72    29    34                 1  
4   174   0.0   112    29    43                 1

In [98]:
print(x.shape)

(23856, 18)


In [99]:
X =x.iloc[:, :-1]
y = x.iloc[:,-1]

In [ ]:
X =x.iloc[:, 2:-1]
y = x.iloc[:,-1]

In [100]:
print(X.shape)
print(y.shape)

(23856, 17)
(23856,)


In [101]:
missing =X.isna().sum(axis=0).sort_values(ascending=False)
missing_value_columns = missing[missing>0]
print('They are %s columns with missing values : \n%s ' %(missing_value_columns.count() , [(index , value) for (index , value) in missing_value_columns.iteritems()]))


They are 1 columns with missing values : 
[('X_12', 182)] 


In [102]:
def impute_value(X):
    dataset =X
    dataset['X_12'].fillna(dataset['X_12'].median() , inplace = True)
    return dataset

X = impute_value(X)

In [103]:
missing =X.isna().sum(axis=0).sort_values(ascending=False)
missing_value_columns = missing[missing>0]
print('They are %s columns with missing values : \n%s ' %(missing_value_columns.count() , [(index , value) for (index , value) in missing_value_columns.iteritems()]))


They are 0 columns with missing values : 
[] 


In [104]:
object = list(X.select_dtypes(include=[np.object]))
print('Here are the %s object variables : \n %s' %(len(object) , object))

Here are the 2 object variables : 
 ['INCIDENT_ID', 'DATE']


In [72]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train ,y_test = train_test_split(X,y , test_size =0.2 , random_state =1)

In [73]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(19084, 15)
(4772, 15)
(19084,)
(4772,)


In [74]:
X_train =X_train.values
# print(X_train.dtypes) :: to checkkk if the X_train is converted into numpy array or not [if error occur it is , if not it's not]
X_test =X_test.values
y_train=y_train.values
y_test =y_test.values
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(19084, 15)
(4772, 15)
(19084,)
(4772,)


In [75]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [76]:
import tensorflow as tf

In [77]:
import keras

In [78]:
ann = tf.keras.models.Sequential()

In [79]:
ann.add(tf.keras.layers.Dense(units=6 ,activation = 'relu'))

In [80]:
ann.add(tf.keras.layers.Dense(units=6 ,activation = 'relu'))

In [81]:
ann.add(tf.keras.layers.Dense(units=1 ,activation = 'sigmoid'))

In [82]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [84]:
ann.fit(X_train, y_train, batch_size = 100, epochs = 100)

Epoch 1/100
19084/19084 [==============================] - 1s 43us/sample - loss: 0.0497 - acc: 0.9816
Epoch 2/100
19084/19084 [==============================] - 1s 47us/sample - loss: 0.0496 - acc: 0.9818
Epoch 3/100
19084/19084 [==============================] - 1s 48us/sample - loss: 0.0495 - acc: 0.9818
Epoch 4/100
19084/19084 [==============================] - 1s 47us/sample - loss: 0.0495 - acc: 0.9818
Epoch 5/100
19084/19084 [==============================] - 1s 50us/sample - loss: 0.0492 - acc: 0.9819
Epoch 6/100
19084/19084 [==============================] - 1s 45us/sample - loss: 0.0492 - acc: 0.9822
Epoch 7/100
19084/19084 [==============================] - 1s 48us/sample - loss: 0.0490 - acc: 0.9817
Epoch 8/100
19084/19084 [==============================] - 1s 45us/sample - loss: 0.0491 - acc: 0.9815
Epoch 9/100
19084/19084 [==============================] - 1s 48us/sample - loss: 0.0488 - acc: 0.9819
Epoch 10/100
19084/19084 [==============================] - 1s 47us/sampl

19084/19084 [==============================] - 1s 50us/sample - loss: 0.0457 - acc: 0.9828
Epoch 80/100
19084/19084 [==============================] - 1s 59us/sample - loss: 0.0459 - acc: 0.9830
Epoch 81/100
19084/19084 [==============================] - 1s 60us/sample - loss: 0.0459 - acc: 0.9828
Epoch 82/100
19084/19084 [==============================] - 1s 57us/sample - loss: 0.0459 - acc: 0.9828
Epoch 83/100
19084/19084 [==============================] - 1s 55us/sample - loss: 0.0455 - acc: 0.9827
Epoch 84/100
19084/19084 [==============================] - 1s 57us/sample - loss: 0.0459 - acc: 0.9828
Epoch 85/100
19084/19084 [==============================] - 1s 57us/sample - loss: 0.0456 - acc: 0.9836
Epoch 86/100
19084/19084 [==============================] - 1s 56us/sample - loss: 0.0455 - acc: 0.9830
Epoch 87/100
19084/19084 [==============================] - 1s 50us/sample - loss: 0.0458 - acc: 0.9828
Epoch 88/100
19084/19084 [==============================] - 1s 47us/sample - 

In [85]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred) , 1) , y_test.reshape(len(y_test) , 1)) ,1))

[[1 1]
 [1 1]
 [1 1]
 ...
 [1 1]
 [1 1]
 [1 1]]


In [86]:
from sklearn.metrics import confusion_matrix , accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score( y_test , y_pred)

[[ 151   82]
 [  19 4520]]


0.9788348700754401

In [91]:
print(f"precision {151/(151+82)}")




#             [[ 151   82]
#              [  19 4520]]

precision 0.648068669527897


In [92]:
print(f" recall {151/(151+19)}")

 recall 0.888235294117647


In [93]:
print(f" f1 square {2* ((65*89)/(65+89))}")

 f1 square 75.12987012987013


In [94]:
print(f" accuracy {(151+4520)/(151+4520+19+82)}")

 accuracy 0.9788348700754401
